=== Artiaga2/1PAW/CodigoDTDyXML/ejercicio_alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Lista">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Asignatura"/>
                <xs:element ref="Alumno"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Alumno">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Apellidos"/>
                <xs:element ref="Nombre"/>
            </xs:choice>
            <xs:attribute name="id"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Nombre" type="xs:string"/>
    <xs:element name="Apellidos" type="xs:string"/>
    <xs:element name="Asignatura">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Hora"/>
                <xs:element ref="Día"/>
            </xs:choice>
            <xs:attribute name="codigo"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Día" type="xs:string"/>
    <xs:element name="Hora" type="xs:string"/>
</xs:schema>

=== Artiaga2/1PAW/CodigoDTDyXML/ejercicio_alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='ejercicio_alumnos.xsd' >
<Alumno id="1">
<Nombre>Arturo</Nombre>
<Apellidos>Pérez Rubio</Apellidos>
</Alumno>
<Alumno id="2">
<Apellidos>Rodríguez García</Apellidos>
<Nombre>Manuel</Nombre>
</Alumno>
<Asignatura codigo="059">Inglés
<Día>Miércoles</Día>
<Hora>12:00</Hora>
</Asignatura>
</Lista>
